---
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  plan:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.25

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
      
      - run: |     
          cd test
          terraform init
          echo 'brrrrrahhhht!'
          mv my-artifact plan.out
          terraform apply "plan.out"
