---
on:
  push:

jobs:
  plan:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.25
      
      - run: |     
          cd test
          terraform init
          terraform plan -out plan.out

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: test/plan.out
          retention-days: 5
